import React from "react";

export const questions=[
    [
        {sentence:"Which of the following is generally the largest use of electricity in a household?"},
        {choice:"refrigerator",tf:true},
        {choice:"lighting equipment",tf:false},
        {choice:"TV",tf:false},
        {choice:"air-conditioning",tf:false},
        {answer:"refrigerator"},
        {commentary:"Electricity consumption can be reduced by not overloading the refrigerator with food, reducing the frequency of opening and closing the refrigerator, and placing the refrigerator slightly away from the wall."},
    ],
    [
        {sentence:"How much more marine life do we have today than in 1970?"},
        {choice:"100%",tf:false},
        {choice:"70%",tf:false},
        {choice:"50%",tf:true},
        {choice:"30%",tf:false},
        {answer:"50%"},
        {commentary:""},
    ],
    [
        {sentence:"What percentage of electricity generated in Japan is from renewable energy sources?"},
        {choice:"54%",tf:false},
        {choice:"32%",tf:false},
        {choice:"18%",tf:true},
        {choice:"9%",tf:false},
        {answer:"18%"},
        {commentary:"In Japan, 76.3% of power generation is fossil fuel fired."},
    ],
    [
        {sentence:"How many centimeters did global average sea level rise between 1902 and 2015?"},
        {choice:"2cm",tf:false},
        {choice:"4cm",tf:false},
        {choice:"8cm",tf:false},
        {choice:"16cm",tf:true},
        {answer:"16cm"},
        {commentary:"An increase of 1°C in seawater temperature from 20°C causes the volume of seawater to expand by approximately 0.025%."},
    ],
    [
        {sentence:"How many tons of new plastic waste are washed into the world's oceans each day?"},
        {choice:"22",tf:false},
        {choice:"220",tf:false},
        {choice:"2200",tf:false},
        {choice:"22000",tf:true},
        {answer:"22000"},
        {commentary:"A total of 8 million tons of plastic waste is washed ashore annually!"},
    ],
    [
        {sentence:"How many pieces of toilet paper can be made from 30 one-liter cartons of milk?"},
        {choice:"1",tf:false},
        {choice:"3",tf:false},
        {choice:"5",tf:true},
        {choice:"7",tf:false},
        {answer:"5"},
        {commentary:""},
    ],
    [
        {sentence:"What is the approximate water content of garbage?"},
        {choice:"10%",tf:false},
        {choice:"30%",tf:false},
        {choice:"50%",tf:false},
        {choice:"80%",tf:true},
        {answer:"80%"},
        {commentary:"Try to drain food scraps and dispose of them in the garbage as much as possible to reduce waste."},
    ],
    [
        {sentence:"What percentage of electricity used in a typical household is standby power?"},
        {choice:"2%",tf:false},
        {choice:"6%",tf:true},
        {choice:"10%",tf:false},
        {choice:"14%",tf:false},
        {answer:"6%"},
        {commentary:"Unplugging frequently will reduce standby power."},
    ],
    [
        {sentence:"How much of the food produced in the world is thrown away?"},
        {choice:"two-thirds",tf:true},
        {choice:"a half",tf:false},
        {choice:"two-sevenths",tf:false},
        {choice:"one-fifteenth",tf:false},
        {answer:"two-thirds"},
        {commentary:""},
    ],
    [
        {sentence:"What percentage of amphibians on Earth are threatened with extinction?"},
        {choice:"11%",tf:false},
        {choice:"21%",tf:false},
        {choice:"31%",tf:false},
        {choice:"41%",tf:true},
        {answer:"41%"},
        {commentary:""},
    ],
];