import React from "react";

export const questions=[
    [
        {sentence:"Which of the following is generally the largest use of electricity in a household?"},
        {choice:"refrigerator",tf:true},
        {choice:"lighting equipment",tf:false},
        {choice:"TV",tf:false},
        {choice:"air-conditioning",tf:false},
        {answer:"refrigerator"},
        {commentary:"Electricity consumption can be reduced by not overloading the refrigerator with food, reducing the frequency of opening and closing the refrigerator, and placing the refrigerator slightly away from the wall."},
    ],
    [
        {sentence:"How much more marine life do we have today than in 1970?"},
        {choice:"100%",tf:false},
        {choice:"70%",tf:false},
        {choice:"50%",tf:true},
        {choice:"30%",tf:false},
        {answer:"50%"},
        {commentary:""},
    ],
    [
        {sentence:"What percentage of electricity generated in Japan is from renewable energy sources?"},
        {choice:"54%",tf:false},
        {choice:"32%",tf:false},
        {choice:"18%",tf:true},
        {choice:"9%",tf:false},
        {answer:"18%"},
        {commentary:"In Japan, 76.3% of power generation is fossil fuel fired."},
    ],
    [
        {sentence:"How many centimeters did global average sea level rise between 1902 and 2015?"},
        {choice:"2cm",tf:false},
        {choice:"4cm",tf:false},
        {choice:"8cm",tf:false},
        {choice:"16cm",tf:true},
        {answer:"16cm"},
        {commentary:"An increase of 1°C in seawater temperature from 20°C causes the volume of seawater to expand by approximately 0.025%."},
    ],
    [
        {sentence:"How many tons of new plastic waste are washed into the world's oceans each day?"},
        {choice:"22",tf:false},
        {choice:"220",tf:false},
        {choice:"2200",tf:false},
        {choice:"22000",tf:true},
        {answer:"22000"},
        {commentary:"A total of 8 million tons of plastic waste is washed ashore annually!"},
    ],
    [
        {sentence:"How many pieces of toilet paper can be made from 30 one-liter cartons of milk?"},
        {choice:"1",tf:false},
        {choice:"3",tf:false},
        {choice:"5",tf:true},
        {choice:"7",tf:false},
        {answer:"5"},
        {commentary:""},
    ],
    [
        {sentence:"What is the approximate water content of garbage?"},
        {choice:"10%",tf:false},
        {choice:"30%",tf:false},
        {choice:"50%",tf:false},
        {choice:"80%",tf:true},
        {answer:"80%"},
        {commentary:"Try to drain food scraps and dispose of them in the garbage as much as possible to reduce waste."},
    ],
    [
        {sentence:"What percentage of electricity used in a typical household is standby power?"},
        {choice:"2%",tf:false},
        {choice:"6%",tf:true},
        {choice:"10%",tf:false},
        {choice:"14%",tf:false},
        {answer:"6%"},
        {commentary:"Unplugging frequently will reduce standby power."},
    ],
    [
        {sentence:"How much of the food produced in the world is thrown away?"},
        {choice:"two-thirds",tf:true},
        {choice:"a half",tf:false},
        {choice:"two-sevenths",tf:false},
        {choice:"one-fifteenth",tf:false},
        {answer:"two-thirds"},
        {commentary:""},
    ],
    [
        {sentence:"What percentage of amphibians on Earth are threatened with extinction?"},
        {choice:"11%",tf:false},
        {choice:"21%",tf:false},
        {choice:"31%",tf:false},
        {choice:"41%",tf:true},
        {answer:"41%"},
        {commentary:""},
    ],
    [
        {sentence:"Approximately how many people worldwide do not have continuous access to safe drinking water?"},
        {choice:"40 million people",tf:false},
        {choice:"400 million people",tf:false},
        {choice:"80 million people",tf:false},
        {choice:"800 million people",tf:true},
        {answer:"800 million people"},
        {commentary:""},
    ],
    [
        {sentence:"How many of the world's population is said to live without electricity?"},
        {choice:"one out of two",tf:false},
        {choice:"one out of four",tf:true},
        {choice:"one out of six",tf:false},
        {choice:"one out of eight",tf:false},
        {answer:"one out of four"},
        {commentary:""},
    ],
    [
        {sentence:"Which creature takes the most human lives in the world?"},
        {choice:"serpent",tf:false},
        {choice:"shark",tf:false},
        {choice:"mosquito",tf:true},
        {choice:"bear",tf:false},
        {answer:"mosquito"},
        {commentary:"Malaria, transmitted by mosquitoes, infects approximately 200 million people annually and causes 430,000 deaths."},
    ],
    [
        {sentence:"How many times has the number of natural disasters affecting people and the number of people affected increased in the 40 years since 1970?"},
        {choice:"Unchanged",tf:false},
        {choice:"twice",tf:false},
        {choice:"three times",tf:false},
        {choice:"five times",tf:true},
        {answer:"five times"},
        {commentary:"Climate change due to global warming is a contributing factor to the recent increase in disasters."},
    ],
    [
        {sentence:"What is called recycling when used plastic is used as a raw material to make new plastic products?"},
        {choice:"material recycling",tf:true},
        {choice:"subject recycling",tf:false},
        {choice:"article recycling",tf:false},
        {choice:"No idea.",tf:false},
        {answer:"material recycling"},
        {commentary:""},
    ],
    [
        {sentence:"Which of the following marks certifies sustainable fisheries (natural marine products)?"},
        {choice:"FSC Certification",tf:false},
        {choice:"Rainforest Alliance Certification",tf:false},
        {choice:"MSC Certification",tf:true},
        {choice:"ASC Certification",tf:false},
        {answer:"MSC Certification"},
        {commentary:"MSC certification is for sustainable fisheries (natural marine products). This certification is for fisheries that meet the highest level of requirements set by the Food and Agriculture Organization of the United Nations (FAO) and other organizations."},
    ],
    [
        {sentence:"In 2019, how many tens of thousands of people worldwide were \" displaced from their homes\" due to conflict or other reasons?"},
        {choice:"3.95 million",tf:false},
        {choice:"39.5 million",tf:false},
        {choice:"7.95 million",tf:false},
        {choice:"79.5 million",tf:true},
        {answer:"79.5 million"},
        {commentary:"This is the largest number since World War II."},
    ],
];