import React from "react";

export const questions=[
    [
    {sentence:"Which of the following is generally the largest use of electricity in a household?"},
    {choice:"refrigerator",tf:true},
    {choice:"lighting equipment",tf:false},
    {choice:"TV",tf:false},
    {choice:"air-conditioning",tf:false},
    {answer:"refrigerator"},
    {commentary:"Electricity consumption can be reduced by not overloading the refrigerator with food, reducing the frequency of opening and closing the refrigerator, and placing the refrigerator slightly away from the wall."},
    ],
    [
        {sentence:"How much more marine life do we have today than in 1970?"},
        {choice:"100%",tf:false},
        {choice:"70%",tf:false},
        {choice:"50%",tf:true},
        {choice:"30%",tf:false},
        {answer:"50%"},
        {commentary:""},
    ],
    [
        {sentence:"What percentage of electricity generated in Japan is from renewable energy sources?"},
        {choice:"54%",tf:false},
        {choice:"32%",tf:false},
        {choice:"18%",tf:true},
        {choice:"9%",tf:false},
        {answer:"18%"},
        {commentary:"In Japan, 76.3% of power generation is fossil fuel fired."},
    ],
    [
        {sentence:"How many centimeters did global average sea level rise between 1902 and 2015?"},
        {choice:"2cm",tf:false},
        {choice:"4cm",tf:false},
        {choice:"8cm",tf:false},
        {choice:"16cm",tf:true},
        {answer:"16cm"},
        {commentary:"An increase of 1°C in seawater temperature from 20°C causes the volume of seawater to expand by approximately 0.025%."},
    ],
    [
        {sentence:"How many tons of new plastic waste are washed into the world's oceans each day?"},
        {choice:"22",tf:false},
        {choice:"220",tf:false},
        {choice:"2200",tf:false},
        {choice:"22000",tf:true},
        {answer:"22000"},
        {commentary:"A total of 8 million tons of plastic waste is washed ashore annually!"},
    ],
    [
        {sentence:"6"},
        {choice:"6",tf:true},
        {choice:"6",tf:false},
        {choice:"6",tf:false},
        {choice:"6",tf:false},
        {answer:"6"},
        {commentary:"commentary"},
    ],
    [
        {sentence:"7"},
        {choice:"7",tf:true},
        {choice:"7",tf:false},
        {choice:"7",tf:false},
        {choice:"7",tf:false},
        {answer:"7"},
        {commentary:"commentary"},
    ],
    [
        {sentence:"8"},
        {choice:"8",tf:true},
        {choice:"8",tf:false},
        {choice:"8",tf:false},
        {choice:"8",tf:false},
        {answer:"8"},
        {commentary:"commentary"},
    ],
    [
        {sentence:"9"},
        {choice:"9",tf:true},
        {choice:"9",tf:false},
        {choice:"9",tf:false},
        {choice:"9",tf:false},
        {answer:"9"},
        {commentary:"commentary"},
    ],
    [
        {sentence:"10"},
        {choice:"10",tf:true},
        {choice:"10",tf:false},
        {choice:"10",tf:false},
        {choice:"10",tf:false},
        {answer:"10"},
        {commentary:"commentary"},
    ],
];